[LOCAL] 
customers.file.path = C:/Spark_data/raw/customers_data_csv/customers.csv
loans.file.path = C:/Spark_data/raw/loans_data_csv/loans_data.csv
loans_defaulters.file.path = C:/Spark_data/raw/loans_defaulters_csv/loans_defaulters.csv
loans_repayments.file.path = C:/Spark_data/raw/loans_repayments_csv/loans_repayments.csv
cleaned.file.path = C:/Spark_data/cleaned
bad.file.path = C:/Spark_data/bad
cleanedNew.file.path = C:/Spark_data/cleaned_new

[TEST]
customers.file.path = C:/Spark_data/raw/customers_data_csv/customers.csv
loans.file.path = C:/Spark_data/raw/loans_data_csv/loans_data.csv
loans_defaulters.file.path = C:/Spark_data/raw/loans_defaulters_csv/loans_defaulters.csv
loans_repayments.file.path = C:/Spark_data/raw/loans_repayments_csv/loans_repayments.csv

[PROD]
customers.file.path = C:/Spark_data/raw/customers_data_csv/customers.csv
loans.file.path = C:/Spark_data/raw/loans_data_csv/loans_data.csv
loans_defaulters.file.path = C:/Spark_data/raw/loans_defaulters_csv/loans_defaulters.csv
loans_repayments.file.path = C:/Spark_data/raw/loans_repayments_csv/loans_repayments.csv