[LOCAL]
spark.app.name = lendingclub-local

[TEST]
spark.app.name = lendingclub-test
spark.executor.instances = 3
spark.executor.cores = 5
spark.executor.memory = 15GB

[PROD]
spark.app.name = lendingclub-prod
spark.executor.instances = 3
spark.executor.cores = 5
spark.executor.memory = 15GB